#!/bin/bash
echo "Enter the File 1: "
read dir1

echo "Enter the File 2: "
read dir2

if [ ! -d $dir1 -o ! -d $dir2 ]; then
    echo "No Such Directory Exist"
    exit 1
fi

subs=`ls $dir1`

for i in $subs; do
  mv "$dir1/$i" "$dir2"
done

echo "Moving Operation Done Successfully"

