#!/bin/bash
echo "Enter the name of the Directory: "
read dir1

if [ ! -d $dir1 ]; then
    echo "No Such Directory Exist"
    exit 1
fi

subs=`ls $dir1`
cnt=0
for i in $subs; do
    if [[ -x "$dir1/$i" ]]
    then
	cnt=$((cnt+1))
    fi
done

echo "Total Executable Number Files $cnt"
