#!/bin/bash
echo "Enter the number of files: "
read N

for ((i=0;i<N;i++)); do
    read fname
    if [ ! -f $fname ]; then
	touch $fname
        echo "File created successfully."
        echo "-----------------------------------"
    else
	mv $fname folder1
	echo "file already exist."
        echo "file moved to folder1 successfully."
        echo "-----------------------------------"
    fi
done
