#!/bin/bash
echo "Enter the Directory Name: "
read dir1
cnt=0
if [ ! -d "$dir1" ]
then 
    echo "Directory Doesn't Exist."
else
    for i in `find $dir1 -type f -size 0`
    do 
        echo "$i"
        rm -r $i
	cnt=$((cnt+1))	
    done
fi
echo "$cnt 0-sized Files Deleted Successfully."

